// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/template.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServiceClient interface {
	SayHi(ctx context.Context, opts ...grpc.CallOption) (MyService_SayHiClient, error)
}

type myServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServiceClient(cc grpc.ClientConnInterface) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) SayHi(ctx context.Context, opts ...grpc.CallOption) (MyService_SayHiClient, error) {
	stream, err := c.cc.NewStream(ctx, &MyService_ServiceDesc.Streams[0], "/proto.MyService/SayHi", opts...)
	if err != nil {
		return nil, err
	}
	x := &myServiceSayHiClient{stream}
	return x, nil
}

type MyService_SayHiClient interface {
	Send(*Greeting) error
	CloseAndRecv() (*Farewell, error)
	grpc.ClientStream
}

type myServiceSayHiClient struct {
	grpc.ClientStream
}

func (x *myServiceSayHiClient) Send(m *Greeting) error {
	return x.ClientStream.SendMsg(m)
}

func (x *myServiceSayHiClient) CloseAndRecv() (*Farewell, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Farewell)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MyServiceServer is the server API for MyService service.
// All implementations must embed UnimplementedMyServiceServer
// for forward compatibility
type MyServiceServer interface {
	SayHi(MyService_SayHiServer) error
	mustEmbedUnimplementedMyServiceServer()
}

// UnimplementedMyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMyServiceServer struct {
}

func (UnimplementedMyServiceServer) SayHi(MyService_SayHiServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedMyServiceServer) mustEmbedUnimplementedMyServiceServer() {}

// UnsafeMyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServiceServer will
// result in compilation errors.
type UnsafeMyServiceServer interface {
	mustEmbedUnimplementedMyServiceServer()
}

func RegisterMyServiceServer(s grpc.ServiceRegistrar, srv MyServiceServer) {
	s.RegisterService(&MyService_ServiceDesc, srv)
}

func _MyService_SayHi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MyServiceServer).SayHi(&myServiceSayHiServer{stream})
}

type MyService_SayHiServer interface {
	SendAndClose(*Farewell) error
	Recv() (*Greeting, error)
	grpc.ServerStream
}

type myServiceSayHiServer struct {
	grpc.ServerStream
}

func (x *myServiceSayHiServer) SendAndClose(m *Farewell) error {
	return x.ServerStream.SendMsg(m)
}

func (x *myServiceSayHiServer) Recv() (*Greeting, error) {
	m := new(Greeting)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MyService_ServiceDesc is the grpc.ServiceDesc for MyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHi",
			Handler:       _MyService_SayHi_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/template.proto",
}
